### ISSUE TITLE
Submodule Openinv not valid link

### ISSUE THREAD

**Issue by smithps** [jsphuebner/stm32-car#1]
Hi,
    I just tried to download the source code for your project as I am interested in converting a 2008 Diesel VW Passat to electric. Note that the link to Submodule libopeninv in this project is broken because the relevant commit is not in that repository.

I have temporarily worked around the problem by downloading that library separately.

Great project by the way !!

**Comment by jsphuebner** [comment]
Thanks :) Fixed.

**Comment by smithps** [comment]
Hi Johannes,
   this is indeed fixed, but now it fails to compile using toolchain gcc-arm-none-eabi-10.3-2021.10 because of the following error cause by terminal.cpp from the included libopeninv:

```
/opt/gcc-arm-none-eabi-10.3-2021.10/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: obj/terminal.o:(.rodata._ZTV8IPutChar[_ZTV8IPutChar]+0x8): undefined reference to `__cxa_pure_virtual'
collect2: error: ld returned 1 exit status
Makefile:75: recipe for target 'stm32_car' failed
make: *** [stm32_car] Error 1
```

It seems that something in the toolchain I am using may have changed from the toolchain you are using, and that you (I?) should define this function - see here: [https://stackoverflow.com/questions/920500/what-is-the-purpose-of-cxa-pure-virtual](url)

I don;t know enough (yet) about your code/project/development environment to be sure of applying a "correct" fix for this, hence I'm reporting it to here for your input.. Sorry to be a pain. 8-(

Please note all I am trying to do at the moment is to download your code and ensure I can compile it.

**Comment by jsphuebner** [comment]
yes with older gcc versions this happens. Easiest fix is to turn on optimize by size (not sure why I turned it off, will update the Makefile). So in Makefile, CPPFLAGS change "-O0 -g3" to "-Os"

**Comment by smithps** [comment]
`yes with older gcc versions this happens. Easiest fix is to turn on optimize by size (not sure why I turned it off, will update the Makefile). So in Makefile, CPPFLAGS change "-O0 -g3" to "-Os"`

Confirm this fixes it and I now can compile the project. Many Thanks.
